#!/bin/sh
set -e
echoerr() { printf "%s\n" "$*" >&2; }

#
# Read environment variables from file if envrionment variable ${1}_FILE is set
#
file_env() {
    local var=""
    local fileVar=""

    eval var="\$${1}"
    eval fileVar="\$${1}_FILE"

    local def="${2:-}"

    if [ -n "${var:-}" ] && [ -n "${fileVar:-}" ]; then
        echo >&2 "error: both ${1} and ${1}_FILE are set (but are exclusive)"
        exit 1
    fi

    local val="$def"

    if [ -n "${var:-}" ]; then
        val="${var}"
    elif [ -n "${fileVar:-}" ]; then
        val="$(cat "${fileVar}")"
    fi

    if [ -n "${val:-}" ]; then
        export "${1}"="$val"
    fi

    unset "${1}_FILE"
}

export ALDIS_CONFIG_PATH="${ALDIS_CONFIG_PATH:-/etc/aldis}"
export ALDIS_DB_PATH="${ALDIS_DB_PATH:-/var/lib/aldis}"
export ALDIS_DB_PORT="${ALDIS_DB_PORT:-}"

file_env 'ALDIS_DB_USER'
file_env 'ALDIS_DB_PASS'
file_env 'ALDIS_ADMIN'
export ALDIS_ADMIN_EMAIL="${ALDIS_ADMIN_EMAIL:-admin@localhost}"
export ALDIS_ADMIN_NAME="${ALDIS_ADMIN_NAME:-Aldis Admin}"
file_env 'ALDIS_ADMIN_PASSWORD'
export ALDIS_LDAP_ACTIVATED="${ALDIS_LDAP_ACTIVATED:-no}"
export ALDIS_LDAP_HOST="${ALDIS_LDAP_HOST:-}"
export ALDIS_LDAP_PORT="${ALDIS_LDAP_PORT:-}"
export ALDIS_LDAP_DN_BIND="${ALDIS_LDAP_DN_BIND:-}"
file_env 'ALDIS_LDAP_PASSWORD'
export ALDIS_LDAP_DN_SEARCH="${ALDIS_LDAP_DN_SEARCH:-}"
export ALDIS_LDAP_MAPPING_USERNAME="${ALDIS_LDAP_MAPPING_USERNAME:-uid}"
export ALDIS_LDAP_MAPPING_FULLNAME="${ALDIS_LDAP_MAPPING_FULLNAME:-cn}"
export ALDIS_LDAP_MAPPING_EMAIL="${ALDIS_LDAP_MAPPING_EMAIL:-mail}"
file_env 'ALDIS_ACCESS_KEY_ENCRYPTION'


[ -d "${ALDIS_CONFIG_PATH}" ] || mkdir -p "${ALDIS_CONFIG_PATH}" || {
    echo "Can't create Aldis config path ${ALDIS_CONFIG_PATH}."
    exit 1
}

[ -d "${ALDIS_DB_PATH}" ] || mkdir -p "${ALDIS_DB_PATH}" || {
    echo "Can't create Aldis data path ${ALDIS_DB_PATH}."
    exit 1
}


#
# Extract database host and port from config.json if they are not set.
# Set default ALDIS_DB_DIALECT and ALDIS_DB_HOST if empty.
#
if [ -z "${ALDIS_DB_DIALECT}" ]; then
    if [ -f "${ALDIS_CONFIG_PATH}/config.json" ]; then
        ALDIS_DB_DIALECT=$(cat "${ALDIS_CONFIG_PATH}/config.json" | jq '.dialect // ""' -r)
    fi
fi

export ALDIS_DB_DIALECT="${ALDIS_DB_DIALECT:-mysql}"

if [ -z "${ALDIS_DB_HOST}" ]; then
    if [ -f "${ALDIS_CONFIG_PATH}/config.json" ]; then
        ALDIS_DB_HOST=$(cat "${ALDIS_CONFIG_PATH}/config.json" | jq ".${ALDIS_DB_DIALECT}.host // \"\"" -r)
    fi
fi

if [ -z "${ALDIS_DB_HOST}" ]; then
    if [ "${ALDIS_DB_DIALECT}" = 'sqlite' ]; then
        export ALDIS_DB_HOST=${ALDIS_DB_PATH}/database.sqlite
    else
        export ALDIS_DB_HOST="${ALDIS_DB_HOST:-0.0.0.0}"
    fi
fi


#
# Remove port number from ALDIS_DB_HOST and put it to ALDIS_DB_PORT
#
case "$ALDIS_DB_HOST" in
  *:*)
    ALDIS_DB_PORT=$(echo "$ALDIS_DB_HOST" | cut -d ':' -f 2)
    ALDIS_DB_HOST=$(echo "$ALDIS_DB_HOST" | cut -d ':' -f 1)
    ;;
  *)
esac


#
# Set ALDIS_DB_PORT if it is not set
#
if [ -z "${ALDIS_DB_PORT}" ]; then
    case ${ALDIS_DB_DIALECT} in
        mysql)
            ALDIS_DB_PORT=3306
            ;;
        postgres)
            ALDIS_DB_PORT=5432
            ;;
        sqlite)
            ;;
        *)
            echoerr "Unknown database dialect: ${ALDIS_DB_DIALECT}"
            exit 1
            ;;
    esac
fi


#
# Ping database if it is not BoltDB
#
if [ "${ALDIS_DB_DIALECT}" != 'sqlite' ]; then
    echoerr "Pinging database on ${ALDIS_DB_HOST} port ${ALDIS_DB_PORT}..."
    TIMEOUT=30


    while ! $(nc -z "$ALDIS_DB_HOST" "$ALDIS_DB_PORT") >/dev/null 2>&1; do
        TIMEOUT=$(expr $TIMEOUT - 1)

        if [ $TIMEOUT -eq 0 ]; then
            echoerr "Could not connect to database server. Exiting."
            exit 1
        fi

        echo -n "."
        sleep 1
    done
    
    export ALDIS_DB_HOST="${ALDIS_DB_HOST}:${ALDIS_DB_PORT}"
fi


#
# Generate new config.json if it does not exist
#
ALDIS_FIRST_RUN=no
if [ ! -f "${ALDIS_CONFIG_PATH}/config.json" ]; then
    ALDIS_FIRST_RUN=yes
    echoerr "Generating setup file ${TMP_STDIN_CONFIG_FILE} ..."

    TMP_STDIN_CONFIG_FILE=$(mktemp)


    ALDIS_TMP_PATH=${ALDIS_TMP_PATH:-/tmp/aldis}
    [ -d "${ALDIS_TMP_PATH}" ] || mkdir -p "${ALDIS_TMP_PATH}" || {
        echo "Can't create Aldis tmp path ${ALDIS_TMP_PATH}."
        exit 1
    }


    case ${ALDIS_DB_DIALECT} in
        mysql)
            ALDIS_DB_DIALECT_ID=1
            ;;
        postgres)
            ALDIS_DB_DIALECT_ID=3
            ;;
        sqlite)
            ALDIS_DB_DIALECT_ID=4
            ;;
        *)
            echoerr "Unknown database dialect: ${ALDIS_DB_DIALECT}"
            exit 1
            ;;
    esac


    cat << EOF > "${TMP_STDIN_CONFIG_FILE}"
${ALDIS_DB_DIALECT_ID}
EOF

    if [ "${ALDIS_DB_DIALECT}" = "sqlite" ]; then
        cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
${ALDIS_DB_HOST}
EOF
    else
        cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
${ALDIS_DB_HOST}
${ALDIS_DB_USER}
${ALDIS_DB_PASS}
${ALDIS_DB:-aldis}
EOF
    fi

    cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
${ALDIS_TMP_PATH}
${ALDIS_WEB_ROOT:-}
no
no
no
no
no
${ALDIS_LDAP_ACTIVATED}
EOF

    if [ "${ALDIS_LDAP_ACTIVATED}" = "yes" ]; then
        cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
${ALDIS_LDAP_HOST}:${ALDIS_LDAP_PORT}
${ALDIS_LDAP_NEEDTLS:-no}
${ALDIS_LDAP_DN_BIND}
${ALDIS_LDAP_PASSWORD}
${ALDIS_LDAP_DN_SEARCH}
${ALDIS_LDAP_SEARCH_FILTER:-(uid=%s)}
${ALDIS_LDAP_MAPPING_DN:-dn}
${ALDIS_LDAP_MAPPING_USERNAME}
${ALDIS_LDAP_MAPPING_FULLNAME}
${ALDIS_LDAP_MAPPING_EMAIL}
EOF
    fi;

    cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
${ALDIS_CONFIG_PATH}
${ALDIS_ADMIN}
${ALDIS_ADMIN_EMAIL}
${ALDIS_ADMIN_NAME}
${ALDIS_ADMIN_PASSWORD}
EOF


    echoerr "Executing aldis setup"
    if test "$#" -ne 1; then
        /usr/local/bin/aldis setup - < "${TMP_STDIN_CONFIG_FILE}"
    else
        "$1" setup - < "${TMP_STDIN_CONFIG_FILE}"
    fi

    rm -f "${TMP_STDIN_CONFIG_FILE}"
fi

#
# Install additional python dependencies
#
if test -f "${ALDIS_CONFIG_PATH}/requirements.txt"; then
    echoerr "Installing additional python dependencies"
    pip3 install --upgrade \
        -r "${ALDIS_CONFIG_PATH}/requirements.txt"
else
    echoerr "No additional python dependencies to install"
fi

#
# Migrate from BoltDB if ALDIS_MIGRATE_FROM_BOLTDB is set (first run only, SQLite only, skipped if DB file already exists)
#
case "${ALDIS_MIGRATE_FROM_BOLTDB:-}" in
    [Tt][Rr][Uu][Ee]|[Yy][Ee][Ss])
        ALDIS_MIGRATE_FROM_BOLTDB="${ALDIS_DB_PATH}/database.boltdb"
        ;;
esac

if [ -n "${ALDIS_MIGRATE_FROM_BOLTDB:-}" ] && [ "${ALDIS_FIRST_RUN}" = "yes" ]; then
    if [ "${ALDIS_DB_DIALECT}" != "sqlite" ]; then
        echoerr "ALDIS_MIGRATE_FROM_BOLTDB is only supported with SQLite dialect, ignoring"
    else
        echoerr "Migrating from BoltDB: ${ALDIS_MIGRATE_FROM_BOLTDB}"
        MIGRATE_ARGS="--from-boltdb=${ALDIS_MIGRATE_FROM_BOLTDB} --merge-existing-users"
        if [ -n "${ALDIS_MIGRATE_SKIP_TASK_OUTPUT:-}" ]; then
            MIGRATE_ARGS="${MIGRATE_ARGS} --skip-task-output"
        fi
        if test "$#" -ne 1; then
            /usr/local/bin/aldis migrate ${MIGRATE_ARGS} --config "${ALDIS_CONFIG_PATH}/config.json"
        else
            "$1" migrate ${MIGRATE_ARGS} --config "${ALDIS_CONFIG_PATH}/config.json"
        fi
    fi
fi

# Import project if environment variable ALDIS_IMPORT_PROJECT_FILE is defined.
# Optionally use ALDIS_IMPORT_PROJECT_NAME to specify the project name.
if [ -n "${ALDIS_IMPORT_PROJECT_FILE:-}" ] && [ "${ALDIS_FIRST_RUN}" = "yes" ]; then
    echoerr "Importing project from ${ALDIS_IMPORT_PROJECT_FILE}"
    IMPORT_ARGS="--file ${ALDIS_IMPORT_PROJECT_FILE}"
    if [ -n "${ALDIS_IMPORT_PROJECT_NAME:-}" ]; then
        echoerr "Using project name: ${ALDIS_IMPORT_PROJECT_NAME}"
        IMPORT_ARGS="${IMPORT_ARGS} --project-name ${ALDIS_IMPORT_PROJECT_NAME}"
    fi
    if test "$#" -ne 1; then
        /usr/local/bin/aldis project import ${IMPORT_ARGS} --config "${ALDIS_CONFIG_PATH}/config.json" || echoerr "Project import failed"
    else
        "$1" project import ${IMPORT_ARGS} || echoerr "Project import failed"
    fi
fi


#
# Start Aldis server
#
echoerr "Starting aldis server"
if test "$#" -ne 1; then
    exec /usr/local/bin/aldis server --config "${ALDIS_CONFIG_PATH}/config.json"
else
    exec "$@"
fi
