version: '3.8'

services:
  ldap:
    image: osixia/openldap:1.4.0
#    container_name: openldap
    environment:
      LDAP_ORGANISATION: "Example Inc."
      LDAP_DOMAIN: "example.org"
      LDAP_ADMIN_PASSWORD: "admin"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d

  ldap_admin:
    image: osixia/phpldapadmin:0.9.0
#    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
    ports:
      - "6443:443"
    depends_on:
      - ldap

  aldis:
    image: globalartinc/aldis:latest
#    container_name: aldis
    environment:
      ALDIS_DB_DIALECT: "sqlite"
      ALDIS_ADMIN_PASSWORD: "changeme"
      ALDIS_ADMIN_NAME: "admin"
      ALDIS_ADMIN_EMAIL: "admin@example.org"
      ALDIS_LDAP_ACTIVATED: "yes"
      ALDIS_LDAP_SERVER: "ldap:389"
      ALDIS_LDAP_SEARCH_DN: "dc=example,dc=org"
      ALDIS_LDAP_BIND_DN: "cn=admin,dc=example,dc=org"
      ALDIS_LDAP_BIND_PASSWORD: "admin"
      ALDIS_LDAP_SEARCH_FILTER: "(&(objectClass=inetOrgPerson)(uid=%s))"
      ALDIS_NON_ADMIN_CAN_CREATE_PROJECT: "yes"
    ports:
      - "3000:3000"
    volumes:
      - aldis_data:/var/lib/aldis
    depends_on:
      - ldap

volumes:
  ldap_data:
  ldap_config:
  aldis_data: